from dataclasses import replace

from projectflow.analysis import add_user_requests, link_request_turns
from projectflow.model import SourceRecord, is_user_prompt
from projectflow.schema import EvidenceValidator, record_evidence


def record(key, role, text, session="s", at="2026-09-26T10:00:00Z"):
    return SourceRecord(key, "claude", session, role, text, {}, recorded_at=at)


def test_only_typed_messages_count_as_user_prompts():
    assert is_user_prompt(record("a", "user", "설치가 자동인가?"))
    assert not is_user_prompt(record("b", "user", "<task-notification>\n<task-id>x</task-id>"))
    assert not is_user_prompt(record("c", "user", "Caveat: The messages below were generated by the user"))
    assert not is_user_prompt(record("d", "assistant", "설치가 자동입니다."))
    assert not is_user_prompt(replace(record("e", "user", "하위 작업 지시"), lineage={"kind": "subagent"}))
    assert not is_user_prompt(replace(record("f", "user", "두 번째 조각"), lineage={"fragment_of": "x", "fragment_index": 2}))


def candidate(key, actor, source, text):
    return {"id": key, "kind": "action", "title": text, "summary": "", "actor": actor, "status": "reported_complete",
            "basis": "explicit_statement", "session_ids": ["s"], "worktree_ids": [], "recorded_at": None,
            "occurred_at": None, "evidence": [{"source_id": source, "start_line": 1, "end_line": 1, "quote": text}]}


def test_extraction_gets_a_question_for_each_user_message_it_skipped():
    ask, other, reply = (record("ask", "user", "문서도 고쳐 줘"), record("other", "user", "좋아. 그렇게 해줘."),
                         record("reply", "assistant", "문서를 고쳤습니다."))
    pool = {r.source_id: r for r in (ask, other, reply)}
    validator = EvidenceValidator(pool, {key: [(1, 1)] for key in pool})
    output = {"event_candidates": [candidate("tmp:1", "assistant", "reply", "문서를 고쳤습니다."),
                                   candidate("tmp:2", "user", "other", "좋아. 그렇게 해줘.")]}
    assert add_user_requests(output, [ask, other, reply], validator) == ["ask"]
    added = output["event_candidates"][-1]
    assert (added["id"], added["kind"], added["status"], added["title"]) == (
        "tmp:user_request_1", "question", "asked", "문서도 고쳐 줘")
    assert add_user_requests({"event_candidates": []}, [ask], validator) == []  # no integration to link it


def test_new_events_hang_from_the_user_message_of_their_turn():
    first, work, test, second, later = (
        record("m1", "user", "설치 스크립트를 만들어 줘", at="2026-09-26T10:00:00Z"),
        record("t1", "tool_call", "Tool: Write\ninstall.sh", at="2026-09-26T10:01:00Z"),
        record("t2", "tool_result", "ok", at="2026-09-26T10:02:00Z"),
        record("m2", "user", "문서도", at="2026-09-26T10:03:00Z"),
        record("t3", "tool_call", "Tool: Edit\nREADME.md", at="2026-09-26T10:04:00Z"))
    other_session = record("x1", "tool_call", "Tool: Edit\nother.py", session="elsewhere", at="2026-09-26T10:05:00Z")
    pool = {r.source_id: r for r in (first, work, test, second, later, other_session)}
    evidence = {item["id"]: item for item in map(record_evidence, pool.values())}
    cite = {item["source_id"]: item["id"] for item in evidence.values()}

    def event(key, source, actor="assistant", kind="action"):
        return {"id": key, "kind": kind, "title": key, "summary": "", "actor": actor, "status": "applied",
                "basis": "tool_record", "session_ids": [pool[source].session_id], "worktree_ids": [],
                "recorded_at": pool[source].recorded_at, "occurred_at": None, "evidence_ids": [cite[source]]}

    base = {"events": [], "edges": []}
    graph = {"events": [event("script", "t1"), event("run", "t2", kind="outcome"), event("docs", "t3"),
                        event("other", "x1")],
             "edges": [{"id": "e1", "from_event_id": "script", "to_event_id": "run", "relation": "verifies",
                        "basis": "explicit", "evidence_ids": [], "rationale": "", "active": True}]}
    result, cited = link_request_turns(graph, base, pool, list(pool), evidence, lambda ids: {}, "run")
    requests = {e["title"]: e for e in result["events"] if e["actor"] == "user"}
    assert set(requests) == {"설치 스크립트를 만들어 줘", "문서도"}  # both messages became nodes
    assert [e["id"] for e in result["events"]][:2] == [requests["설치 스크립트를 만들어 줘"]["id"], "script"]
    turns = {(edge["from_event_id"], edge["to_event_id"]) for edge in result["edges"] if edge["basis"] == "structural"}
    assert turns == {(requests["설치 스크립트를 만들어 줘"]["id"], "script"), (requests["문서도"]["id"], "docs")}
    # `run` is already reached by verifies; `other` has no user message in its session.
    assert all(edge["relation"] == "follows" and edge["origin"] == "dialog_turn"
               for edge in result["edges"] if edge["basis"] == "structural")
    assert result["request_turn_audit"] == {"requests_added": 2, "turn_links": 2}
    assert set(cited) == {cite["m1"], cite["m2"]}
    again, _ = link_request_turns(result, result, pool, list(pool), {**evidence, **cited}, lambda ids: {}, "run")
    assert again["request_turn_audit"] == {"requests_added": 0, "turn_links": 0}


def test_sub_agent_work_hangs_from_the_parent_message_it_ran_under():
    first, second = (record("m1", "user", "리뷰해 줘", at="2026-09-26T10:00:00Z"),
                     record("m2", "user", "배포해 줘", at="2026-09-26T11:00:00Z"))
    task = replace(record("c0", "user", "diff를 검토하라", session="child", at="2026-09-26T10:05:00Z"),
                   lineage={"kind": "subagent", "parent_session_id": "s"})
    found = replace(record("c1", "tool_result", "버그 1건", session="child", at="2026-09-26T10:06:00Z"),
                    lineage={"kind": "subagent", "parent_session_id": "s"})
    pool = {r.source_id: r for r in (first, task, found, second)}
    evidence = {item["id"]: item for item in map(record_evidence, pool.values())}
    cite = {item["source_id"]: item["id"] for item in evidence.values()}
    review = {"id": "review", "kind": "outcome", "title": "리뷰", "summary": "", "actor": "subagent",
              "status": "observed_failure", "basis": "tool_record", "session_ids": ["child"], "worktree_ids": [],
              "recorded_at": found.recorded_at, "occurred_at": None, "evidence_ids": [cite["c1"]]}
    result, _ = link_request_turns({"events": [review], "edges": []}, {"events": [], "edges": []},
                                   pool, list(pool), evidence, lambda ids: {}, "run")
    asked = next(e for e in result["events"] if e["title"] == "리뷰해 줘")
    [link] = [edge for edge in result["edges"] if edge["to_event_id"] == "review"]
    assert (link["from_event_id"], link["origin"]) == (asked["id"], "dialog_turn")
    assert "하위 에이전트" in link["rationale"]
